DROP TABLE IF EXISTS person;

CREATE TABLE PERSON (
  ID                SERIAL       NOT NULL,
  PERSON_DATEBIRTH  DATE         NOT NULL,
  PERSON_NAME       VARCHAR(255) NOT NULL,
  PERSON_SURNAME    VARCHAR(255) NOT NULL,
  PERSON_PATRONYMIC VARCHAR(255) NOT NULL,
  PERSON_IDREQUEST  VARCHAR(255),
  PERSON_INN        VARCHAR(255)
);
